# Generated by Django 3.0.8 on 2021-03-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asha_profile',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
