# Generated by Django 3.0.8 on 2021-03-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_auto_20210323_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asha_Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=20)),
                ('Comment', models.TextField()),
                ('Report', models.FileField(upload_to='Asha/Reports')),
                ('Date', models.DateField()),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.Asha_Profile')),
            ],
        ),
    ]
