# Generated by Django 3.0.8 on 2021-03-27 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_auto_20210326_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asha_Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.CharField(max_length=15)),
                ('Amount_Paid', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.Asha_Profile')),
            ],
        ),
    ]
