# Generated by Django 3.0.8 on 2021-03-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('Auth_Id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=5, null=True)),
                ('Address', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=50)),
                ('Distrct', models.CharField(max_length=50)),
                ('Pan_Mun', models.CharField(max_length=50)),
                ('Ward', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50)),
                ('Status', models.CharField(default='Tobit', max_length=5)),
                ('Created_Date', models.DateField()),
            ],
        ),
    ]
