# Generated by Django 3.0.8 on 2021-03-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asha', '0006_auto_20210325_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='Auth_Id',
        ),
    ]
