# Generated by Django 3.1.7 on 2021-04-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asha', '0012_auto_20210419_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMembers',
        ),
    ]
