# Generated by Django 3.1.7 on 2021-04-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asha', '0013_delete_familymembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=5)),
                ('Relationship', models.CharField(max_length=15)),
                ('Marital', models.CharField(max_length=10, null=True)),
                ('Phone', models.CharField(max_length=15)),
                ('Status', models.CharField(max_length=10, null=True)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asha.basicdetails')),
            ],
        ),
    ]
