# Generated by Django 3.1.7 on 2021-05-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asha', '0015_baby'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Asha_Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Pregnancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('LMP', models.DateField()),
                ('Weeks', models.CharField(max_length=5)),
                ('Blood', models.CharField(max_length=5)),
                ('Weight', models.CharField(max_length=10)),
                ('Health', models.CharField(max_length=30)),
                ('Hospital', models.CharField(max_length=25)),
                ('Doctor', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=15)),
                ('Register_Date', models.DateField()),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asha.basicdetails')),
            ],
        ),
        migrations.CreateModel(
            name='User_Palliative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Mobile', models.CharField(max_length=15)),
                ('Issue', models.CharField(max_length=20)),
                ('Comments', models.CharField(max_length=35)),
                ('Register_Date', models.DateField()),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asha.basicdetails')),
            ],
        ),
    ]
