# Generated by Django 3.1.7 on 2021-05-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asha', '0018_user_palliative_user_pregnancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Asha_Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
