# Generated by Django 3.0.8 on 2021-03-25 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asha', '0005_baby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='Auth_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asha.BasicDetails'),
        ),
    ]
