# Generated by Django 3.0.8 on 2021-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asha', '0008_baby_auth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Asha_Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
