# Generated by Django 3.1.7 on 2021-03-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Asha', '0010_user_palliative_user_pregnancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_palliative',
            name='Auth_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asha.basicdetails'),
        ),
        migrations.AlterField(
            model_name='user_pregnancy',
            name='Auth_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asha.basicdetails'),
        ),
    ]
