# Generated by Django 3.0.8 on 2021-03-23 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asha_Profile',
            fields=[
                ('Auth_Id', models.TextField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Qual', models.CharField(max_length=10)),
                ('Mobile', models.CharField(max_length=15)),
                ('Aadhar', models.CharField(max_length=20)),
                ('Blood', models.CharField(max_length=5)),
                ('Addr1', models.CharField(max_length=50)),
                ('Addr2', models.CharField(max_length=50)),
                ('Addr3', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=15)),
                ('Aadhar_Id', models.FileField(upload_to='Asha/Id/Documents')),
                ('Addres_Id', models.FileField(upload_to='Asha/Addres/Documents')),
                ('Bank_Account', models.CharField(max_length=50)),
                ('Bank_Name', models.CharField(max_length=20)),
                ('Account_Number', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pension', models.CharField(max_length=10)),
                ('Salary', models.CharField(max_length=10)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.Asha_Profile')),
            ],
        ),
    ]
