# Generated by Django 3.0.8 on 2021-03-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_asha_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asha_Contact_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('User_Info', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.Asha_Profile')),
            ],
        ),
    ]
