# Generated by Django 3.0.8 on 2021-03-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_asha_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='asha_profile',
            name='Owner',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asha_profile',
            name='Panchayath',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asha_profile',
            name='Ward',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
