# Generated by Django 3.1.7 on 2021-04-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0008_auto_20210327_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asha_insurance',
            name='Auth_Id',
        ),
        migrations.RemoveField(
            model_name='asha_reports',
            name='Auth_Id',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Asha_Insurance',
        ),
        migrations.DeleteModel(
            name='Asha_Reports',
        ),
    ]
