# Generated by Django 3.1.7 on 2021-04-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_auto_20210419_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asha_Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=20)),
                ('Comment', models.TextField()),
                ('Feedback', models.TextField(null=True)),
                ('Report', models.FileField(upload_to='Asha/Reports')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=20, null=True)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.asha_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Asha_Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.CharField(max_length=15)),
                ('Amount_Paid', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.asha_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pension', models.CharField(max_length=10)),
                ('Salary', models.CharField(max_length=10)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.asha_profile')),
            ],
        ),
    ]
