# Generated by Django 3.1.7 on 2021-04-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0010_account_asha_insurance_asha_reports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
