# Generated by Django 3.0.8 on 2021-03-22 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Profile',
            fields=[
                ('Auth_Id', models.TextField(primary_key=True, serialize=False)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Mobile', models.IntegerField()),
                ('image', models.ImageField(default='default.png', upload_to='Organizer/Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
