# Generated by Django 3.0.8 on 2021-03-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='State_Name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=30)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.State')),
            ],
        ),
    ]
