# Generated by Django 3.1.7 on 2021-04-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_reports',
            name='Auth_Id',
        ),
        migrations.DeleteModel(
            name='Org_Profile',
        ),
        migrations.DeleteModel(
            name='Org_Reports',
        ),
    ]
