# Generated by Django 3.1.7 on 2021-04-06 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0002_auto_20210406_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Profile',
            fields=[
                ('Auth_Id', models.TextField(primary_key=True, serialize=False)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=50, null=True)),
                ('District', models.CharField(max_length=50, null=True)),
                ('Mobile', models.IntegerField()),
                ('image', models.ImageField(default='default.png', upload_to='Organizer/Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Org_Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=20)),
                ('Comment', models.TextField()),
                ('Report', models.FileField(upload_to='Organizer/Reports')),
                ('Date', models.DateField()),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.org_profile')),
            ],
        ),
    ]
