# Generated by Django 3.1.7 on 2021-04-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_org_profile_org_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_reports',
            name='Auth_Id',
        ),
        migrations.RemoveField(
            model_name='pan_mun',
            name='District',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='Panchayath',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Org_Reports',
        ),
        migrations.DeleteModel(
            name='Pan_Mun',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
