# Generated by Django 3.1.7 on 2021-04-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20210409_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=30)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.state')),
            ],
        ),
        migrations.CreateModel(
            name='Pan_Mun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Panchayath_Name', models.CharField(max_length=30)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.district')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ward_Name', models.CharField(max_length=30)),
                ('Panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.pan_mun')),
            ],
        ),
    ]
