# Generated by Django 3.1.7 on 2021-04-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_district_pan_mun_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pan_mun',
            name='District',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='Panchayath',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Pan_Mun',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
