# Generated by Django 3.0.8 on 2021-03-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20210323_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pan_Mun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Panchayath_Name', models.CharField(max_length=30)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.District')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ward_Name', models.CharField(max_length=30)),
                ('Panchayath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Pan_Mun')),
            ],
        ),
    ]
