# Generated by Django 3.2.3 on 2021-05-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Addr1', models.CharField(max_length=50)),
                ('Addr2', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pin', models.CharField(max_length=10)),
                ('Amount', models.CharField(max_length=10, null=True)),
                ('Card', models.CharField(max_length=30)),
                ('Card_Name', models.CharField(max_length=30)),
            ],
        ),
    ]
